### ISSUE TITLE
refresh_token

### ISSUE THREAD

**Issue by lmaister** [deafgreatdane/google_oauth_calendar#1]
So the offline access generates the refresh_token.

Are there any plans to add the request of new auth token using the refresh_token for persistent authorization?

**Comment by deafgreatdane** [comment]
Ah, this question finally makes sense to me after I experienced the behavior of google's access token expiring while my rails session was still active.

I'll work on a tweak to the generators to default to the "offline" mode that captures the refresh token and auto refreshes it.

**Comment by deafgreatdane** [comment]
I've updated the gem to 0.3, now capturing the refresh token and access token expiration. The ClientBuilder class is now used to generate a google client, and it either uses the access token, or refreshes it from the refresh token.
